apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y21xl3zmp-nodejs
  janus-idp.io/tekton: y21xl3zmp-nodejs
  backstage.io/kubernetes-id: y21xl3zmp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y21xl3zmp-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
