apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y21xl3zmp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y21xl3zmp-nodejs 
  name: y21xl3zmp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: y21xl3zmp-nodejs 
